// <auto-generated />
namespace Restauracja.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class AddSent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSent));
        
        string IMigrationMetadata.Id
        {
            get { return "202010281140420_AddSent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
